using REPOJP.StageRoles;
using UnityEngine;
int checks=0;
void Check(bool value,string label){if(!value)throw new Exception(label);checks++;}
TrackerSample S(float distance=20,float bearing=0,int id=1,int height=0,bool head=false)=>head?
    new(null,new TrackerContact(id,distance,bearing,height,"Bob")):new(new TrackerContact(id,distance,bearing,height),null);
TrackerRules rules=new();
Check(rules.Choose(0,new(null,null),8,5)==TrackerNotice.None,"No empty startup report");
Check(rules.Choose(0,S(),8,5)==TrackerNotice.Enemy,"Enemy acquired");
rules.Delivered(0,TrackerNotice.Enemy,S(),20);
Check(rules.Choose(200,S(19,20),8,5)==TrackerNotice.None,"Small movements do not repeat");
Check(rules.Choose(19.9f,S(10),8,5)==TrackerNotice.None,"Ordinary cooldown");
Check(rules.Choose(20,S(15),8,5)==TrackerNotice.Enemy,"Distance threshold");
Check(rules.Choose(20,S(20,60),8,5)==TrackerNotice.Enemy,"Direction threshold");
Check(rules.Choose(20,S(20,0,1,1),8,5)==TrackerNotice.Enemy,"Elevation change");
Check(rules.Choose(20,S(20,0,2),8,5)==TrackerNotice.Enemy,"Target switch");
Check(rules.Choose(1,S(8),8,5)==TrackerNotice.Danger,"Close warning bypasses normal cooldown");
rules.Delivered(1,TrackerNotice.Danger,S(8),20);
Check(rules.Choose(100,S(8),8,5)==TrackerNotice.None,"Standing danger does not repeat");
rules.Observe(100,S(9),8);rules.Observe(104,S(9),8);
Check(rules.Choose(104,S(8),8,5)==TrackerNotice.None,"8m boundary jitter cannot rearm");
rules.Observe(105,S(12),8);rules.Observe(107,S(12),8);
Check(rules.Choose(107,S(8),8,5)==TrackerNotice.None,"Clear period required");
rules.Observe(108,S(12),8);
Check(rules.Choose(108,S(8),8,5)==TrackerNotice.Danger,"Sustained withdrawal rearms warning");
rules.Delivered(108,TrackerNotice.Danger,S(8),20);
rules.Observe(109,S(12),8);rules.Observe(113,S(12),8);
Check(rules.Choose(114,S(8),8,5)==TrackerNotice.None,"Warning cooldown still enforced after rearm");
Check(rules.Choose(128,S(8),8,5)==TrackerNotice.Danger,"Warning rearms after full interval");
rules=new();rules.Delivered(0,TrackerNotice.Enemy,S(20,179),20);
Check(rules.Choose(20,S(20,-179),8,5)==TrackerNotice.None,"Angle wraps through rear without false turn");
Check(new TrackerRules().Choose(0,S(2),0,5)==TrackerNotice.Enemy,"Zero danger range disables warning only");
rules=new();var both=new TrackerSample(S().Enemy,S(80,90,2,1,true).Head);
rules.Delivered(0,TrackerNotice.Enemy,both,20);
Check(rules.Choose(20,new(S(10).Enemy,both.Head),8,5)==TrackerNotice.Head,"Head reports cannot starve behind moving enemies");
rules.Delivered(20,TrackerNotice.Head,both,20);
Check(rules.Choose(40,new(S(10).Enemy,S(100,0,3,0,true).Head),8,5)==TrackerNotice.Enemy,"Normal reports alternate when both change");
Check(rules.Choose(40,new(null,both.Head),8,5)==TrackerNotice.Enemy,"Departure reported");
rules.Delivered(40,TrackerNotice.Enemy,new(null,both.Head),20);
Check(rules.Choose(70,new(null,both.Head),8,5)==TrackerNotice.None,"Clear report not repeated");
Check(TrackerRules.Message(TrackerNotice.Head,S(81.2f,-90,2,-1,true))=="Head:Bob:Left:Below:82m","Compact head directions and ceiling distance");
foreach(var (angle,name) in new[]{(0f,"Front"),(45f,"FrontRight"),(90f,"Right"),(135f,"BackRight"),(180f,"Back"),(-135f,"BackLeft"),(-90f,"Left"),(-45f,"FrontLeft")})
    Check(S(10,angle).Enemy!.Value.Describe("Enemy")==$"Enemy:{name}:10m","Eight directions: "+name);
// Production runtime with native scene and queue stand-ins.
StageRolesConfig config=null!;RoleNotifier notifier=null!;TrackerRoleRuntime runtime=null!;List<RoleAssignment> players=null!;EnemyParent parent=null!;Enemy enemy=null!;EnemyHealth health=null!;
void Fresh(){Time.time=0;config=new();notifier=new();runtime=new(config,notifier);players=new(){new(new PlayerAvatar())};EnemyDirector.instance=new();PrivatePlayerSpeech.Sent.Clear();PrivatePlayerSpeech.Succeeds=true;
    enemy=new();enemy.transform.position=new(0,0,20);health=new();parent=new();parent.Children[typeof(Enemy)]=enemy;parent.Children[typeof(EnemyHealth)]=health;EnemyDirector.instance.enemiesSpawned.Add(parent);}
void Tick(float t){Time.time=t;runtime.Tick(players);}
string Last()=>PrivatePlayerSpeech.Sent.Last().Text;
Fresh();Tick(0);Check(notifier.Pending.Count==1,"One report queued");Tick(1);Check(notifier.Pending.Count==1,"Waiting report does not accumulate");
enemy.transform.position=new(12,0,0);notifier.Flush();Check(Last()=="Enemy:Right:12m","Latest target location is used at dispatch");
Check(PrivatePlayerSpeech.Sent[0].Receiver==players[0].Player,"Private recipient is Tracker");
Tick(2);Check(notifier.Pending.Count==0,"No immediate duplicate after delivery");
enemy.transform.position=new(7,0,0);Tick(3);notifier.Flush();Check(Last()=="Danger:Right:7m","Danger bypass through runtime");
Fresh();Tick(0);enemy.transform.position=new(40,0,0);notifier.Flush();Check(PrivatePlayerSpeech.Sent.Count==0,"Out-of-range target disappears before send");
enemy.transform.position=new(0,0,20);Tick(1);notifier.Flush();Check(PrivatePlayerSpeech.Sent.Count==1,"Cancelled report spends no cooldown");
Fresh();Tick(0);players[0].Role=StageRole.Runner;notifier.Flush();Check(PrivatePlayerSpeech.Sent.Count==0,"Role loss cancels pending report");
Fresh();Tick(0);players[0].Player.Living=false;notifier.Flush();Check(PrivatePlayerSpeech.Sent.Count==0,"Death cancels pending report");
Fresh();Tick(0);runtime.Stop();notifier.Flush();Check(PrivatePlayerSpeech.Sent.Count==0,"Stage end invalidates pending report");
Fresh();Tick(0);runtime.Forget(players[0]);notifier.Flush();Check(PrivatePlayerSpeech.Sent.Count==0,"Role reset invalidates pending report");
Fresh();Tick(0);players.Clear();notifier.Flush();Check(PrivatePlayerSpeech.Sent.Count==0,"Disconnected Tracker invalidated");
Fresh();Tick(0);players[0].Player=new();notifier.Flush();Check(PrivatePlayerSpeech.Sent.Count==0,"Old avatar invalidated");
Fresh();Tick(0);notifier.Expire();Tick(1);Check(notifier.Pending.Count==1,"Expired queue releases pending state");
Fresh();notifier.Accept=false;Tick(0);notifier.Accept=true;Tick(1);Check(notifier.Pending.Count==1,"Queue refusal retries without locking");
Fresh();PrivatePlayerSpeech.Succeeds=false;Tick(0);notifier.Flush();PrivatePlayerSpeech.Succeeds=true;Tick(1);notifier.Flush();Check(PrivatePlayerSpeech.Sent.Count==1,"Transport failure spends no cooldown");
Fresh();parent.Spawned=false;Tick(0);Check(notifier.Pending.Count==0,"Pooled enemy excluded");
Fresh();enemy.CurrentState=EnemyState.Spawn;Tick(0);Check(notifier.Pending.Count==0,"Spawning enemy excluded");
Fresh();enemy.CurrentState=EnemyState.Despawn;Tick(0);Check(notifier.Pending.Count==0,"Despawning enemy excluded");
Fresh();health.dead=true;Tick(0);Check(notifier.Pending.Count==0,"Dead enemy excluded");
Fresh();parent.gameObject.activeInHierarchy=false;Tick(0);Check(notifier.Pending.Count==0,"Inactive parent excluded");
Fresh();enemy.CurrentState=EnemyState.Stunned;Tick(0);Check(notifier.Pending.Count==1,"Living stunned enemy retained");
Fresh();config.AnnouncementsEnabled.Value=false;Tick(0);Check(notifier.Pending.Count==0,"Announcements toggle respected");
Fresh();players[0].Player.photonView!.Owner=null;Tick(0);Check(notifier.Pending.Count==0,"Unavailable owner excluded");
Fresh();players[0].Role=StageRole.Superbot;Tick(0);Check(notifier.Pending.Count==1,"Superbot gets Tracker capability");
Fresh();EnemyDirector.instance.enemiesSpawned.Clear();var victim=new PlayerAvatar{Name="Test Player",Living=false,Head=new()};victim.Head.transform.position=new(0,5,-60);players.Add(new(victim,StageRole.Runner));Tick(0);notifier.Flush();
Check(Last()=="Head:TestPlayer:Back:Above:61m","Head tracking beyond enemy range, elevation and compact name");
victim.Living=true;Tick(20);notifier.Flush();Check(Last()=="Head:Clear","Revived head removed");
Fresh();config.TrackerEnemyRange.Value=8;enemy.transform.position=new(0,0,7);Tick(0);notifier.Flush();enemy.transform.position=new(0,0,9);Tick(1);Tick(5);enemy.transform.position=new(0,0,7);Tick(21);notifier.Flush();
Check(PrivatePlayerSpeech.Sent.Count==1,"Custom detection boundary cannot defeat warning hysteresis");
Console.WriteLine($"PASS: {checks} production Tracker rules/runtime checks; networking and scene objects use stand-ins.");
